# Generated by Django 3.0.6 on 2020-06-05 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endpoints', '0003_mlalgorithm_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mlalgorithmstatus',
            name='parentAlgorithm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='endpoints.MlAlgorithm'),
        ),
    ]
